M48
; DRILL file {KiCad 9.0.1} date 2025-05-21T17:24:45-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-21T17:24:45-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.100
%
G90
G05
T1
X159.447Y-68.992
X159.447Y-74.772
T2
X127.0Y-88.392
X129.54Y-88.392
M30
